#loader contenttweaker

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Fluid;
import mods.contenttweaker.Color;

function createFluid(nameString as string, colorString as string, temperature as int = 300){
	var thisFluid = VanillaFactory.createFluid(nameString, Color.fromHex(colorString));
	thisFluid.temperature = (temperature);
	thisFluid.register();
}

createFluid("blackfluid", "090909", 1350);
createFluid("lumin", "bab709", 700);
createFluid("bisphenolb", "6B5802", 700);
createFluid("ic2coolant", "185EAD", 700);
createFluid("tetraethylene", "4a4a4a");
createFluid("moltenpulsatingiron", "33A61C", 1300);
createFluid("moltenresonantseaborgium", "54D66B", 1800);
createFluid("moltenmodularium", "FFFFFF", 1400);
createFluid("moltencompressediron", "363636", 2300);
createFluid("cryogeniccoolant", "BDECFC", 0);
createFluid("primalquarkdegeneratematterplasma", "A39090", 230000);
createFluid("moltenemerald", "1AFF00", 800);
createFluid("highlycomplicatedcosmicrubber", "6C706E", 80000);
createFluid("draconiumenrichedamonia", "EA00FF", 400);
createFluid("steamcrackeddraconiumenrichedamonia", "EA00FF", 400);
createFluid("draconiumcontainingmixture", "EA00FF", 400);
createFluid("enhanceddraconiummixture", "EA00FF", 400);
createFluid("draconiumsaltmixture", "EA00FF", 400);
createFluid("aircompresseddsm", "EA00FF", 400);
createFluid("draconiumdioxide", "EA00FF", 400);
createFluid("draconiumhexachloride", "EA00FF", 400);
createFluid("draconiumhexafluoride", "EA00FF", 400);
createFluid("draconiumnitradesolution", "EA00FF", 400);
createFluid("depleteddraconiumnitradesolution", "EA00FF", 400);
createFluid("draconiumrichsolution", "EA00FF", 400);
createFluid("obisdianinfuseddraconiummixture", "EA00FF", 1400);
createFluid("pvtchs", "C1D111", 1400);
createFluid("moltenvibrantalloy", "38C20E", 1400);
createFluid("plutoniumbasedliquidfuel", "EB1010");
createFluid("plutoniumbasedliquidfuele", "C41010");
createFluid("uraniumbasedliquidfuel", "034314");
createFluid("uraniumbasedliquidfuele", "034b16");
createFluid("moltentungsticnaquadah", "1F1F1F", 1600);
createFluid("sterilizedbiocatalystmedium", "237A10", 2600);
createFluid("rawsterilizedbiocatalystmedium", "2E871A");
createFluid("naqudahasphalt", "137009", 1300);
createFluid("moderatelycrackednaquadahasphalt", "227033", 1300);
createFluid("acidnaquadahemulsion", "444A45", 2300);
createFluid("naquadahemulsion", "2C2E2C", 1800);
createFluid("bisphenolc", "5D6575", 2300);
createFluid("monazitecakesolution", "2A751B", 2300);
createFluid("monazitefilteredcakesolution", "1B5710", 2300);
createFluid("monazitefilteredsolution", "294207", 2300);
createFluid("fentanyl", "F8FCCC", 1200);
createFluid("Desomorphine", "DCFCCF", 1200);
createFluid("moltenprotoadamantiumplatedalloy", "252b7a", 1800);
createFluid("protoadamantiumalloycatalyst", "2c3393", 2200);
createFluid("molteninfnite", "6099C4", 9999);
createFluid("zeliusactivationfluid", "734ca4");
createFluid("dissolvingfluid", "CFD8DC");
createFluid("aluminosilicatewoolsolution", "8A8A8A");
createFluid("thorium_emulsion", "495B49");
createFluid("low_thorium_solution", "0C220C");
createFluid("radioactive_sludge", "885B49");
createFluid("radium_emulsion", "7E7E85");
createFluid("radium_sodium_solution", "7E7E97");
createFluid("radium_cake_solution", "666B66");
createFluid("radium_sodium_emulsion", "666B66");
createFluid("solardistilledwater", "40b0ed");
createFluid("dirtywater", "6e3415");
createFluid("superlubricenttincture", "5a5c00");
createFluid("paraphenylenediaminesolution", "BA68C8");
createFluid("nmethyl2pyrrolidone", "81D4FA");
createFluid("bbutyrolactone", "C8E6C9");
createFluid("twonaphthol", "FFAB91");
createFluid("binol", "37474F");
createFluid("diketene", "B0BEC5");
createFluid("chlorodiphenylphosphine", "BA68C8");
createFluid("unrefinedkevlar", "FFEB3B");
createFluid("terephtaladehyde", "CFD8DC");
createFluid("carbondisulfide", "4DB6AC");
createFluid("naphtalene", "FF8F00");
createFluid("butylithium", "C2185B");
createFluid("liquidbinap", "263238");
createFluid("crystalkevlar", "FFEE58");
createFluid("supraplasma", "cba3cc");
createFluid("metastableenergeticalalloy", "db4234");
createFluid("purifiedthoriumemulsion", "388E3C");
createFluid("driedthoriumemulsion", "305731");
createFluid("sulfuricthoriumsolution", "FF7043");
createFluid("hydrocrackedthoriumsolution", "A5D6A7");
createFluid("thoriumsolution", "2E7D32");
createFluid("heatedthoriumsolution", "DCE775");
createFluid("supercooledthoriumsolution", "B3E5FC");
createFluid("thoriumleachsolution", "06521c");
createFluid("tungstalloytwo", "06521c");
createFluid("livingsolder", "886C62");
createFluid("mutatedlivingsolder", "694653");
createFluid("explosivehydrazine", "827722");
createFluid("sulfurousacid", "827722");
createFluid("hundretmethanol", "827722");
createFluid("hundretbutanol", "827722");
createFluid("propionicacid", "E0E0E0");
createFluid("nickeltetracarbonyl", "B7D7F0");
createFluid("trimethylborate", "D7CCC8");
createFluid("hexanol", "B71C1C");
createFluid("polyurethaneresin", "C3B640");
createFluid("diaminodiphenylmethanemixture", "E1BEE7");
createFluid("diphenylmethanediiscocyanatemixture", "DFC9E2");
createFluid("siliconoil", "D4D4D4");
createFluid("pentanol", "EF9A9A");
createFluid("pentoldehyde", "EF9A9A");
createFluid("isopentoldehyde", "EF9A9A");
createFluid("sterilebiomedium", "1B5E20");
createFluid("moltenredstonealloy", "822020");
createFluid("isohexanoldehyde", "B71C1C");
createFluid("hexanoldehyde", "B71C1C");
createFluid("dilutedoil", "141414");
createFluid("desaltedoil", "2C2C2C");
createFluid("sulfuricoilresidues", "FFEE58");
createFluid("sulfuricbyproducts", "2C2C2C");
createFluid("heavyoilresidues", "181816");
createFluid("fractionatedoil", "181816");
createFluid("tar", "222121");
createFluid("oilgas", "121010");
createFluid("vacuumflashedtar", "121010");
createFluid("richamine", "121010");
createFluid("sourgas", "121010");
createFluid("oilfractions", "121010");
createFluid("treatedsulfuricfractions", "121010");
createFluid("uncatalyzedsulfuricgas", "D4E157");
createFluid("wastewater", "2E4D7F");
createFluid("fluegas", "B1B1B0");
createFluid("muddybastnasitesolution", "842508");
createFluid("conditionedbastnasitemud", "544340");
createFluid("dilutedbastnasitemud", "2E4D7F");
createFluid("filteredbsatnasitemud", "2E4D7F");
createFluid("wetbastnasiterareearthconcentrate", "2E4D7F");
createFluid("bastnasiteconcentrate", "2E4D7F");
createFluid("ethanolgasoline", "2E4D7F");
createFluid("impureferrocenemixture", "8E24AA");
createFluid("ether", "E65100");
createFluid("ferrocenesolution", "B0BEC5");
createFluid("acidicbastnasiteconcentrate", "BF360C");
createFluid("ceriumcontainingbastnasiteconcentrate", "BF5D40");
createFluid("bastnasiterarerearthoxidemixture", "D28770");
createFluid("bastnasiterarerearthconcentrate", "2E4D7F");
createFluid("nitrogenatedbastnasiterarerearthoxides", "2E4D7F");
createFluid("bastnasiterarerearthoxidesemulsion", "2E4D7F");
createFluid("bastnasiterarerearthoxidessolution", "2E4D7F");
createFluid("diethylamine", "827717");
createFluid("ferrocenewaste", "827717");
createFluid("bastnasiteoxidecompositeliquid", "827717");
createFluid("waterplasma", "827717");
createFluid("geneticmutagen", "448247");
createFluid("xenoxene", "4D4C4C");
createFluid("rawradox", "8E24AA");
createFluid("lightradox", "D0AADB");
createFluid("heavyradox", "633C7A");
createFluid("crackedlightradox", "B9A1C7");
createFluid("purifiedradox", "321245");
createFluid("crackedheavyradox", "6A1B9A");
createFluid("borontrioxide", "64695D");
createFluid("sodiumchloride", "5B6787");
createFluid("unprocessedboronsolution", "739993");
createFluid("liquidboronnanoparticles", "739993");
createFluid("refinedglue", "A9AD21");
createFluid("naquadahactivationliquid", "2b1303");
createFluid("iron4chloride", "424242");
createFluid("moltenrawneutronium", "F5F2D6");
createFluid("hyperreactiveliquid", "773693");
createFluid("moltenlegendarium", "c3c3c3");
createFluid("moltenlanthanumfullerenenanotubes", "59335c");
createFluid("moltenactiniumsuperhydride", "8c273f");
createFluid("moltenchargedcesiumceriumcobaltindium", "296b0a");
createFluid("moltenborocarbide", "679112");
createFluid("moltenfullerenesuperconductor", "74eb1a");
createFluid("moltenrheniumhassiumthalliumisophtaloylbisdiethylthiourea", "85428a");
createFluid("creatium", "7B1FA2");
createFluid("manasolution", "51A3E5");
createFluid("distilledmana", "4A90C9");
createFluid("dissolutedmana", "76A6CD");
createFluid("highmana", "B1CADD");
createFluid("thoriumleach", "B1CADD");
createFluid("activatedthoriumsolution", "004D40");
createFluid("moltenenhancedenderium", "113817");
createFluid("moltenawakenedcompressedmetal", "ab4b1b");
createFluid("liquidrawneutronium", "F5F2D6");
createFluid("photopolymer", "4CAF50");
createFluid("hydrogentetrafluoride", "90CAF9");
createFluid("hydrogentetrafluoromehtane", "8D6E63");
createFluid("hydrogentetrafluorocarbidedioxide", "F8BBD0");
createFluid("fluorohydrideammoniumcarbamat", "2E7D32");
createFluid("lanthanumyttriumsolution", "615263");
createFluid("lanthanumceriumacidicsolution", "A1887F");
createFluid("ceriumlanthanumsaturatedcompoundsolution", "FFE0B2");
createFluid("moltenceriumdopedlanthanum", "F3EDBF");
createFluid("unprocessedcelasolution", "D9DF95");
createFluid("moltencelananoparticles", "D9DF95");
createFluid("moltencelananocarbides", "AB47BC");
createFluid("moltenceriumlanthanum", "D9DF95");
createFluid("lanthanumceriumsolution", "E2E7B3");
createFluid("usedphotopolymersolution", "CE93D8");
createFluid("extradistilledwater", "BBDEFB");
createFluid("quaternaryammonium", "CFD8DC");
createFluid("roastedbastnasiteconcentrate", "2E4D7F");
createFluid("jetfuel", "429D46");
createFluid("combustionpromoter", "2E4D7F");
createFluid("pcbb", "9C27B0");

